/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pa;

/**
 *
 * @author User
 */
public class frmPrincipal extends javax.swing.JDialog {

    /** Creates new form frmPrincipal */
    public frmPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTermo1 = new javax.swing.JLabel();
        lblTermoGeral = new javax.swing.JLabel();
        lblRazao = new javax.swing.JLabel();
        txfTermo1 = new javax.swing.JTextField();
        txfTermoGeral = new javax.swing.JTextField();
        txfRazao = new javax.swing.JTextField();
        btnPA = new javax.swing.JButton();
        lblLinha1 = new javax.swing.JLabel();
        lblLinha2 = new javax.swing.JLabel();
        lblLinha3 = new javax.swing.JLabel();
        lblLinha4 = new javax.swing.JLabel();
        lblLinha5 = new javax.swing.JLabel();
        btnPG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora de PA e PG");

        lblTermo1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblTermo1.setText("Primeiro termo      (a1):");

        lblTermoGeral.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblTermoGeral.setText("Enésimo termo        (n):");

        lblRazao.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblRazao.setText("Razão/Incremento (r/q):");

        txfTermo1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        txfTermoGeral.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        txfRazao.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N

        btnPA.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnPA.setText("PA");
        btnPA.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPAActionPerformed(evt);
            }
        });

        lblLinha1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblLinha1.setText("Linha 1:");

        lblLinha2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblLinha2.setText("Linha 2:");

        lblLinha3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblLinha3.setText("Linha 3:");

        lblLinha4.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblLinha4.setText("Linha 4:");

        lblLinha5.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblLinha5.setText("Linha 5:");

        btnPG.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        btnPG.setText("PG");
        btnPG.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPGActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblLinha1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblLinha2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblLinha3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblLinha4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblLinha5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(btnPA)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(lblRazao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, lblTermoGeral, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, lblTermo1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txfTermo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txfTermoGeral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txfRazao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnPG))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTermo1)
                    .add(txfTermo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTermoGeral)
                    .add(txfTermoGeral, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblRazao)
                    .add(txfRazao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnPA)
                    .add(btnPG))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLinha1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLinha2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLinha3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLinha4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblLinha5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPAActionPerformed
        try{
        double a1 = 0.0;
        double razao = 0.0;
        double geral = 0.0;
        
        a1 = Double.parseDouble(txfTermo1.getText());
        geral = Double.parseDouble(txfTermoGeral.getText());
        razao = Double.parseDouble(txfRazao.getText());
        
        double parent = geral - 1;
        double multi = parent * razao;
        double soma = a1 + multi;
        lblLinha1.setText("Linha 1:   an = a1 + (n - 1) * r");
        lblLinha2.setText("Linha 2:   a("+Double.toString(geral).format("%.2f", geral)+") = ("+Double.toString(a1).format("%.2f", a1)+") + ("+Double.toString(geral).format("%.2f", geral)+" - 1) * ("+Double.toString(razao).format("%.2f", razao)+")");
        lblLinha3.setText("Linha 3:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(a1).format("%.2f", a1)+" + "+Double.toString(parent).format("%.2f", parent)+" * "+Double.toString(razao).format("%.2f", razao));
        lblLinha4.setText("Linha 4:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(a1).format("%.2f", a1)+" + "+Double.toString(multi).format("%.2f", multi));
        lblLinha5.setText("Linha 5:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(soma).format("%.2f", soma));
        }
        
        catch (Exception e)
        {
            if (txfTermo1.getText().isEmpty() && txfTermoGeral.getText().isEmpty() && txfRazao.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha os campos com números.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
        
            else if (txfTermo1.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o primeiro campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else if (txfTermoGeral.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o segundo campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else if (txfRazao.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o terceiro campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Digite números válidos.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
        }
    }//GEN-LAST:event_btnPAActionPerformed

    private void btnPGActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPGActionPerformed
    {//GEN-HEADEREND:event_btnPGActionPerformed
        try{
        double a1 = 0.0;
        double razao = 0.0;
        double geral = 0.0;
        
        a1 = Double.parseDouble(txfTermo1.getText());
        geral = Double.parseDouble(txfTermoGeral.getText());
        razao = Double.parseDouble(txfRazao.getText());

        double subt = geral - 1;
        double pot = Math.pow(razao, subt);
        double mult = a1 * pot;
        lblLinha1.setText("Linha 1:   an = a1 * q^n-1");
        lblLinha2.setText("Linha 2:   a("+Double.toString(geral).format("%.2f", geral)+") = ("+Double.toString(a1).format("%.2f", a1)+") * ("+Double.toString(razao).format("%.2f", razao)+")^("+Double.toString(geral).format("%.2f", geral)+")-1");
        lblLinha3.setText("Linha 3:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(a1).format("%.2f", a1)+" * "+Double.toString(razao).format("%.2f", razao)+"^"+Double.toString(subt).format("%.2f", subt));
        lblLinha4.setText("Linha 4:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(a1).format("%.2f", a1)+" * "+Double.toString(pot).format("%.2f", pot));
        lblLinha5.setText("Linha 5:   a"+Double.toString(geral).format("%.2f", geral)+" = "+Double.toString(mult).format("%.2f", mult));
        }
        
        catch (Exception e)
        {
            if (txfTermo1.getText().isEmpty() && txfTermoGeral.getText().isEmpty() && txfRazao.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha os campos com números.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
        
            else if (txfTermo1.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o primeiro campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else if (txfTermoGeral.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o segundo campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else if (txfRazao.getText().isEmpty())
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Preencha o terceiro campo.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
            
            else
            {
                lblLinha1.setText(" ");
                lblLinha2.setText(" ");
                lblLinha3.setText("          Digite números válidos.");
                lblLinha4.setText(" ");
                lblLinha5.setText(" ");
            }
        }
    }//GEN-LAST:event_btnPGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPA;
    private javax.swing.JButton btnPG;
    private javax.swing.JLabel lblLinha1;
    private javax.swing.JLabel lblLinha2;
    private javax.swing.JLabel lblLinha3;
    private javax.swing.JLabel lblLinha4;
    private javax.swing.JLabel lblLinha5;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblTermo1;
    private javax.swing.JLabel lblTermoGeral;
    private javax.swing.JTextField txfRazao;
    private javax.swing.JTextField txfTermo1;
    private javax.swing.JTextField txfTermoGeral;
    // End of variables declaration//GEN-END:variables

}